name: Deploy to AWS S3

on:
  push:
    branches: [ "main" ]
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: NodeJS Setup
      uses: actions/setup-node@v4
      with:
        node-version: ${{ secrets.NODE_VERSION }}
    - run: npm install
    - run: npm run build
    
    - uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    
    - run: aws s3 sync build s3://coupon-app-frontend --delete # deploy